/*
 * DialogNewFile.java
 *
 * Created on July 27, 2006, 5:43 PM
 */

package mlnr.gui.dlg;

import java.text.DecimalFormat;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.NumberFormatter;
import java.util.prefs.*;

import mlnr.Measurement;
import mlnr.util.InterfaceSettings;

/**
 *
 * @author  Robert Molnar II
 */
public class DialogNewFile extends javax.swing.JDialog {
    
    private boolean ok = false;
    
    private float fDesignWidth;
    private float fDesignHeight;
    
    /** Default size of a design. */
    private static float fDefaultWidth = 100.0f;
    private static float fDefaultHeight = 100.0f;
    
    /** Creates new form DialogNewFile */
    public DialogNewFile(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        getRootPane().setDefaultButton(jButtonOk);
        
        jLabelWidth.setText(Measurement.getTextualName());
        jLabelHeight.setText(Measurement.getTextualName());
        jFormattedTextFieldWidth.setFormatterFactory(new DefaultFormatterFactory(new NumberFormatter(new DecimalFormat("#.##"))));
        jFormattedTextFieldHeight.setFormatterFactory(new DefaultFormatterFactory(new NumberFormatter(new DecimalFormat("#.##"))));
        
        jFormattedTextFieldWidth.setValue(Measurement.convertMeasurement(DialogNewFile.getDefaultWidth(), 2));
        jFormattedTextFieldHeight.setValue(Measurement.convertMeasurement(DialogNewFile.getDefaultHeight(), 2));
                
        setLocation(DialogUtil.centerDialog(parent.getBounds(), getBounds()));
        
    }
    
    /** This will get the settings.
     */
    public static InterfaceSettings getSettings() {
        return new DialogNewFileSettings();
    }

    /** This will restore settings to the initial factory settings.
     */
    public static void restoreFactorSettings() {
        setDefaultHeight(100.0f);
        setDefaultWidth(100.0f);
        getSettings().save();
    }
    
    /** This will set the width in measurement.
     * @param measurement is the new default width for a new design.
     */
    public static void setDefaultWidth(float measurement) {
        fDefaultWidth = measurement;
    }
    
    /** This will set the width in measurement.
     * @param measurement is the new default height for a new design.
     */
    public static void setDefaultHeight(float measurement) {
        fDefaultHeight = measurement;
    }
    
    /** @return the width of the default pad size.
     */
    public static float getDefaultWidth() {
        return fDefaultWidth;
    }
    
    /** @return the height of the default pad size.
     */
    public static float getDefaultHeight() {
        return fDefaultHeight;
    }

    /** @return true if the user clicked on save.
     */
    public boolean isOk() {
        return ok;
    }
    
    /** This will get the design width.
     * @return design width in measurements.
     */
    public float getDesignWidth() {
        return Measurement.convReal(Float.parseFloat(jFormattedTextFieldWidth.getValue().toString()));
    }
    
    /** This will get the design height.
     * @return design height in measurements.
     */
    public float getDesignHeight() {
        return Measurement.convReal(Float.parseFloat(jFormattedTextFieldHeight.getValue().toString()));
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jFormattedTextFieldWidth = new javax.swing.JFormattedTextField();
        jFormattedTextFieldHeight = new javax.swing.JFormattedTextField();
        jLabelWidth = new javax.swing.JLabel();
        jLabelHeight = new javax.swing.JLabel();
        jButtonOk = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();

        jLabel2.setText("jLabel2");
        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("New File");
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Drawing Size"));
        jLabel1.setText("Width:");

        jLabel3.setText("Height:");

        jFormattedTextFieldWidth.setText("jFormattedTextField1");

        jFormattedTextFieldHeight.setText("jFormattedTextField2");

        jLabelWidth.setText("jLabel5");

        jLabelHeight.setText("jLabel6");

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel1)
                    .add(jLabel3))
                .add(11, 11, 11)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jFormattedTextFieldWidth, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                    .add(jFormattedTextFieldHeight, 0, 0, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabelWidth)
                    .add(jLabelHeight))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(jLabelWidth)
                    .add(jFormattedTextFieldWidth, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel3)
                    .add(jLabelHeight)
                    .add(jFormattedTextFieldHeight, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButtonOk.setText("Ok");
        jButtonOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOkActionPerformed(evt);
            }
        });

        jButtonCancel.setText("Cancel");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(jButtonCancel)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jButtonOk))
                    .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jButtonOk)
                    .add(jButtonCancel))
                .addContainerGap())
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
// TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void jButtonOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOkActionPerformed
// TODO add your handling code here:
        setVisible(false);
        ok = true;
    }//GEN-LAST:event_jButtonOkActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DialogNewFile(new javax.swing.JFrame(), true).setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonOk;
    private javax.swing.JFormattedTextField jFormattedTextFieldHeight;
    private javax.swing.JFormattedTextField jFormattedTextFieldWidth;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelHeight;
    private javax.swing.JLabel jLabelWidth;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
    
}

    
/** This will save the vertex settings
 */
class DialogNewFileSettings implements InterfaceSettings {
    static private String WIDTH = "DialogNewFileSetWidthFloat"; // float
    static private String HEIGHT = "DialogNewFileSetHeightFloat"; // float

    public DialogNewFileSettings() {        
    }
    
    public void save() {
        Preferences prefs = Preferences.userNodeForPackage(mlnr.embd.Version.getVersion());
        prefs.putFloat(WIDTH, DialogNewFile.getDefaultWidth());
        prefs.putFloat(HEIGHT, DialogNewFile.getDefaultHeight());
    }
    
    public void load() {
        Preferences prefs = Preferences.userNodeForPackage(mlnr.embd.Version.getVersion());
        DialogNewFile.setDefaultWidth(prefs.getFloat(WIDTH, DialogNewFile.getDefaultWidth()));
        DialogNewFile.setDefaultHeight(prefs.getFloat(HEIGHT, DialogNewFile.getDefaultHeight()));
    }
}
