/*
 * DialogGridSettings.java
 *
 * Created on January 27, 2007, 10:05 AM
 */

package mlnr.gui.dlg;

import java.awt.Color;
import javax.swing.ButtonGroup;
import javax.swing.JColorChooser;
import mlnr.Measurement;

/**
 *
 * @author  Robert Molnar II
 */
public class DialogGridSettings extends javax.swing.JDialog {
    ButtonGroup buttonGroup = new ButtonGroup();
    Color gridColor = Measurement.getGridColor();
    Color gridFineColor = Measurement.getFineGridColor();
    
    /** Creates new form DialogGridSettings */
    public DialogGridSettings(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        // Group up the radio buttons.
        buttonGroup.add(jRadioButtonGridSize1);
        buttonGroup.add(jRadioButtonGridSize2);
        buttonGroup.add(jRadioButtonGridSize3);
        buttonGroup.add(jRadioButtonGridSize4);
        
        // Load the grid settings.
        loadSettings();
        
        setLocation(DialogUtil.centerDialog(parent.getBounds(), getBounds()));
    }
    
    /** This will load the settings for the options in this dialog box.
     */
    public void loadSettings() {
        loadSettingsGridValues();
        
        jCheckBoxUseFineGrid.setSelected(Measurement.isFineGridVisible());
        
        // Set the fine grid setting.
        if (Measurement.isMetric()) {
            switch (Measurement.getFineGridType()) {
                case Measurement.MM_1:
                    jRadioButtonGridSize1.setSelected(true);
                    break;
                case Measurement.MM_2:
                    jRadioButtonGridSize2.setSelected(true);
                    break;
                case Measurement.MM_5:
                    jRadioButtonGridSize3.setSelected(true);
                    break;
            }
            jRadioButtonGridSize4.setVisible(false);
        } else {
            switch (Measurement.getFineGridType()) {
                case Measurement.IN_1_16:
                    jRadioButtonGridSize1.setSelected(true);
                    break;
                case Measurement.IN_1_8:
                    jRadioButtonGridSize2.setSelected(true);
                    break;
                case Measurement.IN_1_4:
                    jRadioButtonGridSize3.setSelected(true);
                    break;
                case Measurement.IN_1_2:
                    jRadioButtonGridSize4.setSelected(true);
                    break;
            }
        }
    }
    
    /** This will setup the grid size values for the fine grid.
     */
    private void loadSettingsGridValues() {
        if (Measurement.isMetric()) {
            jLabelGridSize.setText("10 mm");
            jRadioButtonGridSize1.setText("1 mm");
            jRadioButtonGridSize2.setText("2 mm");
            jRadioButtonGridSize3.setText("5 mm");
            jRadioButtonGridSize4.setEnabled(false);
        } else {
            jLabelGridSize.setText("1 inch");
            jRadioButtonGridSize1.setText("1/16 inch");
            jRadioButtonGridSize2.setText("1/8 inch");
            jRadioButtonGridSize3.setText("1/4 inch");
            jRadioButtonGridSize4.setText("1/2 inch");
            jRadioButtonGridSize4.setEnabled(true);
        }
    }
    
    /** @return the grid type selected.
     */
    private int getGridType() {
        if (Measurement.isMetric()) {
            if (jRadioButtonGridSize1.isSelected())
                return Measurement.MM_1;
            else if (jRadioButtonGridSize2.isSelected())
                return Measurement.MM_2;
            else if (jRadioButtonGridSize3.isSelected())
                return Measurement.MM_5;
            throw new IllegalStateException("Metric cannot choose option 4.");
        } else {
            if (jRadioButtonGridSize1.isSelected())
                return Measurement.IN_1_16;
            else if (jRadioButtonGridSize2.isSelected())
                return Measurement.IN_1_8;
            else if (jRadioButtonGridSize3.isSelected())
                return Measurement.IN_1_4;
            else if (jRadioButtonGridSize4.isSelected())
                return Measurement.IN_1_2;
        }
        
        throw new IllegalStateException("Unknown grid type choice.");
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelGridSize = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jRadioButtonGridSize1 = new javax.swing.JRadioButton();
        jRadioButtonGridSize2 = new javax.swing.JRadioButton();
        jRadioButtonGridSize3 = new javax.swing.JRadioButton();
        jRadioButtonGridSize4 = new javax.swing.JRadioButton();
        jCheckBoxUseFineGrid = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        jButtonChooseGridColor = new javax.swing.JButton();
        jButtonChooseFineGridColor = new javax.swing.JButton();
        jButtonRestoreFactoryColor = new javax.swing.JButton();
        jButtonSaveAsDefault = new javax.swing.JButton();
        jButtonOk = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Change Grid Settings");
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Grid Size"));
        jLabel1.setText("Grid Size:");

        jLabelGridSize.setText("jLabel2");

        jLabel3.setText("Fine Grid Size:");

        jRadioButtonGridSize1.setText("jRadioButton1");
        jRadioButtonGridSize1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jRadioButtonGridSize1.setMargin(new java.awt.Insets(0, 0, 0, 0));

        jRadioButtonGridSize2.setText("jRadioButton2");
        jRadioButtonGridSize2.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jRadioButtonGridSize2.setMargin(new java.awt.Insets(0, 0, 0, 0));

        jRadioButtonGridSize3.setText("jRadioButton3");
        jRadioButtonGridSize3.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jRadioButtonGridSize3.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jRadioButtonGridSize3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonGridSize3ActionPerformed(evt);
            }
        });

        jRadioButtonGridSize4.setText("jRadioButton4");
        jRadioButtonGridSize4.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jRadioButtonGridSize4.setMargin(new java.awt.Insets(0, 0, 0, 0));

        jCheckBoxUseFineGrid.setText("Use Fine Grid Setting");
        jCheckBoxUseFineGrid.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jCheckBoxUseFineGrid.setMargin(new java.awt.Insets(0, 0, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelGridSize))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButtonGridSize2)
                            .addComponent(jRadioButtonGridSize1)
                            .addComponent(jRadioButtonGridSize3)
                            .addComponent(jRadioButtonGridSize4)))
                    .addComponent(jCheckBoxUseFineGrid))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabelGridSize))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jRadioButtonGridSize1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonGridSize2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonGridSize3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonGridSize4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jCheckBoxUseFineGrid))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Grid Colors"));
        jButtonChooseGridColor.setText("Choose Grid Color");
        jButtonChooseGridColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonChooseGridColorActionPerformed(evt);
            }
        });

        jButtonChooseFineGridColor.setText("Choose Fine Grid Color");
        jButtonChooseFineGridColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonChooseFineGridColorActionPerformed(evt);
            }
        });

        jButtonRestoreFactoryColor.setText("Restore Factory Color");
        jButtonRestoreFactoryColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRestoreFactoryColorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonChooseGridColor, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                    .addComponent(jButtonChooseFineGridColor, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                    .addComponent(jButtonRestoreFactoryColor, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jButtonChooseGridColor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonChooseFineGridColor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonRestoreFactoryColor)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jButtonSaveAsDefault.setText("Save As Default");
        jButtonSaveAsDefault.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveAsDefaultActionPerformed(evt);
            }
        });

        jButtonOk.setText("Ok");
        jButtonOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOkActionPerformed(evt);
            }
        });

        jButtonCancel.setText("Cancel");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonSaveAsDefault)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCancel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonOk))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonOk)
                    .addComponent(jButtonCancel)
                    .addComponent(jButtonSaveAsDefault))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void jButtonOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOkActionPerformed
// TODO add your handling code here:
        Measurement.saveSettings(gridColor, gridFineColor, jCheckBoxUseFineGrid.isSelected(), getGridType());
        setVisible(false);
    }//GEN-LAST:event_jButtonOkActionPerformed
    
    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
// TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButtonCancelActionPerformed
    
    private void jButtonSaveAsDefaultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveAsDefaultActionPerformed
// TODO add your handling code here:
        Measurement.saveSettings(gridColor, gridFineColor, jCheckBoxUseFineGrid.isSelected(), getGridType());
        Measurement.getSettings().save();
    }//GEN-LAST:event_jButtonSaveAsDefaultActionPerformed
    
    private void jButtonRestoreFactoryColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRestoreFactoryColorActionPerformed
// TODO add your handling code here:
        Measurement.restoreColorSettings();
        gridColor = Measurement.getGridColor();
        gridFineColor = Measurement.getFineGridColor();
        
    }//GEN-LAST:event_jButtonRestoreFactoryColorActionPerformed
    
    private void jButtonChooseFineGridColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonChooseFineGridColorActionPerformed
// TODO add your handling code here:
        Color c = JColorChooser.showDialog(this, "Fine Grid Color", Measurement.getFineGridColor());
        if (c != null)
            gridFineColor = c;
    }//GEN-LAST:event_jButtonChooseFineGridColorActionPerformed
    
    private void jButtonChooseGridColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonChooseGridColorActionPerformed
// TODO add your handling code here:
        Color c = JColorChooser.showDialog(this, "Grid Color", Measurement.getGridColor());
        if (c != null)
            gridColor = c;
    }//GEN-LAST:event_jButtonChooseGridColorActionPerformed
    
    private void jRadioButtonGridSize3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonGridSize3ActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonGridSize3ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DialogGridSettings(new javax.swing.JFrame(), true).setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonChooseFineGridColor;
    private javax.swing.JButton jButtonChooseGridColor;
    private javax.swing.JButton jButtonOk;
    private javax.swing.JButton jButtonRestoreFactoryColor;
    private javax.swing.JButton jButtonSaveAsDefault;
    private javax.swing.JCheckBox jCheckBoxUseFineGrid;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelGridSize;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButtonGridSize1;
    private javax.swing.JRadioButton jRadioButtonGridSize2;
    private javax.swing.JRadioButton jRadioButtonGridSize3;
    private javax.swing.JRadioButton jRadioButtonGridSize4;
    // End of variables declaration//GEN-END:variables
    
}
