/*
 * DialogSetLighteningColor.java
 *
 * Created on August 16, 2005, 3:43 PM
 */

package mlnr.gui.dlg;

import java.text.DecimalFormat;
import javax.swing.*;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.NumberFormatter;
import mlnr.Measurement;
import mlnr.gui.cpnt.DrawingPad;
import mlnr.gui.cpnt.ImageInfo;
import mlnr.util.InterfaceSettings;

/**
 *
 * @author  Robert Molnar II
 */
public class DialogImageSettings extends javax.swing.JDialog {    
    
    // <editor-fold defaultstate="collapsed" desc=" Fields ">
    
    ButtonGroup buttonGroup = new ButtonGroup();

    /** This is true if the lightening or DPI setting is changed. */
    boolean needReloadImages = false;
    
    // </editor-fold>
    
    /** Creates new form DialogSetLighteningColor */
    public DialogImageSettings(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        buttonGroup.add(jRadioButtonHeight);
        buttonGroup.add(jRadioButtonWidth);
        
        jFormattedTextFieldWidth.setFormatterFactory(new DefaultFormatterFactory(new NumberFormatter(new DecimalFormat("#.##"))));
        jFormattedTextFieldHeight.setFormatterFactory(new DefaultFormatterFactory(new NumberFormatter(new DecimalFormat("#.##"))));
        jFormattedTextFieldLightenPercentage.setFormatterFactory(new DefaultFormatterFactory(new NumberFormatter(new DecimalFormat("#.##"))));
        jFormattedTextFieldDPI.setFormatterFactory(new DefaultFormatterFactory(new NumberFormatter(new DecimalFormat("#.##"))));
        
        jLabelWidth.setText(Measurement.getTextualName());
        jLabelHeight.setText(Measurement.getTextualName());
        
        initSettings();
        
        getRootPane().setDefaultButton(jButtonOk);
    }
    
    /** @return true if the images need to be reloaded.
     */
    public boolean isNeedReload() {
        return needReloadImages;
    }
    
    /** This will initial the settings in this dialog box.
     */
    private void initSettings() {
        jFormattedTextFieldLightenPercentage.setValue(ImageInfo.getImageLightenPercentage() * 100);
        jFormattedTextFieldDPI.setValue(ImageInfo.getDPI());
        jFormattedTextFieldWidth.setValue(ImageInfo.getDefaultSizeWidth());
        jFormattedTextFieldHeight.setValue(ImageInfo.getDefaultSizeHeight());
        jCheckBoxUseImageSize.setSelected(ImageInfo.isUseDefaultSize());
        if (ImageInfo.isUseWidthOrHeight())
            jRadioButtonWidth.setSelected(true);
        else
            jRadioButtonHeight.setSelected(true);
    }
    
    /** This will set the settings.
     */
    private void setSettings() {        
        float imageLightenPercentage = Float.parseFloat(jFormattedTextFieldLightenPercentage.getValue().toString()) / 100;
        float imageDPI = Float.parseFloat(jFormattedTextFieldDPI.getValue().toString());
        
        if (Math.abs(imageLightenPercentage - ImageInfo.getImageLightenPercentage()) > 0.0001)
            needReloadImages = true;
        if (imageDPI != ImageInfo.getDPI())
            needReloadImages = true;
        
        ImageInfo.setImageLightenPercentage(imageLightenPercentage);
        ImageInfo.setDPI(imageDPI);
        ImageInfo.setDefaultSizeWidth(Float.parseFloat(jFormattedTextFieldWidth.getValue().toString()));
        ImageInfo.setDefaultSizeHeight(Float.parseFloat(jFormattedTextFieldHeight.getValue().toString()));
        ImageInfo.setUseDefaultSize(jCheckBoxUseImageSize.isSelected());
        ImageInfo.setUseWidthOrHeight(jRadioButtonWidth.isSelected());
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jFormattedTextFieldLightenPercentage = new javax.swing.JFormattedTextField();
        jButtonOk = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jFormattedTextFieldWidth = new javax.swing.JFormattedTextField();
        jFormattedTextFieldHeight = new javax.swing.JFormattedTextField();
        jRadioButtonWidth = new javax.swing.JRadioButton();
        jRadioButtonHeight = new javax.swing.JRadioButton();
        jCheckBoxUseImageSize = new javax.swing.JCheckBox();
        jLabelWidth = new javax.swing.JLabel();
        jLabelHeight = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jFormattedTextFieldDPI = new javax.swing.JFormattedTextField();
        jButtonSaveCurrentSettingsAsDefault = new javax.swing.JButton();
        jButtonRestoreDefault = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Set Image Lightening Percentage");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Lightening Percentage"));

        jLabel1.setText("Lightening Percentage [0 - 100]:");

        jFormattedTextFieldLightenPercentage.setText("jFormattedTextField1");

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(2, 2, 2)
                .add(jLabel1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jFormattedTextFieldLightenPercentage, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 48, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(jFormattedTextFieldLightenPercentage, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );

        jButtonOk.setText("Ok");
        jButtonOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOkActionPerformed(evt);
            }
        });

        jButtonCancel.setText("Cancel");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Initial Size Of Image"));

        jLabel2.setText("Width:");

        jLabel3.setText("Height:");

        jFormattedTextFieldWidth.setText("jFormattedTextField1");

        jFormattedTextFieldHeight.setText("jFormattedTextField2");

        jRadioButtonWidth.setText("Use Width");
        jRadioButtonWidth.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jRadioButtonWidth.setMargin(new java.awt.Insets(0, 0, 0, 0));

        jRadioButtonHeight.setText("Use Height");
        jRadioButtonHeight.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jRadioButtonHeight.setMargin(new java.awt.Insets(0, 0, 0, 0));

        jCheckBoxUseImageSize.setText("Enable Initial Size");
        jCheckBoxUseImageSize.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jCheckBoxUseImageSize.setMargin(new java.awt.Insets(0, 0, 0, 0));

        jLabelWidth.setText("jLabel5");

        jLabelHeight.setText("jLabel6");

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel2)
                    .add(jLabel3))
                .add(12, 12, 12)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jFormattedTextFieldHeight, 0, 0, Short.MAX_VALUE)
                    .add(jFormattedTextFieldWidth, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabelWidth)
                    .add(jLabelHeight))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jRadioButtonHeight)
                    .add(jRadioButtonWidth)))
            .add(jCheckBoxUseImageSize)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(jFormattedTextFieldWidth, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabelWidth)
                    .add(jRadioButtonWidth))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel3)
                    .add(jFormattedTextFieldHeight, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabelHeight)
                    .add(jRadioButtonHeight))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jCheckBoxUseImageSize)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("DPI Setting"));

        jLabel4.setText("DPI:");

        jFormattedTextFieldDPI.setText("jFormattedTextField1");

        org.jdesktop.layout.GroupLayout jPanel4Layout = new org.jdesktop.layout.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel4Layout.createSequentialGroup()
                .add(jLabel4)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jFormattedTextFieldDPI, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 88, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(98, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                .add(jLabel4)
                .add(jFormattedTextFieldDPI, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );

        jButtonSaveCurrentSettingsAsDefault.setText("Save As Default");
        jButtonSaveCurrentSettingsAsDefault.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveCurrentSettingsAsDefaultActionPerformed(evt);
            }
        });

        jButtonRestoreDefault.setText("Restore Factory Defaults");
        jButtonRestoreDefault.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRestoreDefaultActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(jButtonRestoreDefault)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jButtonSaveCurrentSettingsAsDefault)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jButtonCancel)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jButtonOk))
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jPanel1, 0, 104, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jButtonOk)
                    .add(jButtonCancel)
                    .add(jButtonSaveCurrentSettingsAsDefault)
                    .add(jButtonRestoreDefault))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-499)/2, (screenSize.height-180)/2, 499, 180);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        if (needReloadImages)
            new JOptionPane().showMessageDialog(this, "Images need to be reloaded because Lightening Percentage or DPI Setting was changed. Can take a few seconds to perform.", "Images Need To Be Reloaded", JOptionPane.WARNING_MESSAGE);
        setVisible(false);
        
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void jButtonSaveCurrentSettingsAsDefaultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveCurrentSettingsAsDefaultActionPerformed
// TODO add your handling code here:
        setSettings();
        ImageInfo.getSettings().save();
        
    }//GEN-LAST:event_jButtonSaveCurrentSettingsAsDefaultActionPerformed

    private void jButtonRestoreDefaultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRestoreDefaultActionPerformed
// TODO add your handling code here:
        ImageInfo.restoreAllSettings();
        initSettings();
        
    }//GEN-LAST:event_jButtonRestoreDefaultActionPerformed

    private void jButtonOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOkActionPerformed
        setSettings();
        if (needReloadImages)
            new JOptionPane().showMessageDialog(this, "Images need to be reloaded because Lightening Percentage or DPI Setting was changed. Can take a few seconds to perform.", "Images Need To Be Reloaded", JOptionPane.WARNING_MESSAGE);
        setVisible(false);
    }//GEN-LAST:event_jButtonOkActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() { 
                new DialogImageSettings(new javax.swing.JFrame(), true).setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonOk;
    private javax.swing.JButton jButtonRestoreDefault;
    private javax.swing.JButton jButtonSaveCurrentSettingsAsDefault;
    private javax.swing.JCheckBox jCheckBoxUseImageSize;
    private javax.swing.JFormattedTextField jFormattedTextFieldDPI;
    private javax.swing.JFormattedTextField jFormattedTextFieldHeight;
    private javax.swing.JFormattedTextField jFormattedTextFieldLightenPercentage;
    private javax.swing.JFormattedTextField jFormattedTextFieldWidth;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelHeight;
    private javax.swing.JLabel jLabelWidth;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRadioButtonHeight;
    private javax.swing.JRadioButton jRadioButtonWidth;
    // End of variables declaration//GEN-END:variables
    
}
