/*
 * DialogDollie.java
 *
 * Created on August 11, 2008, 3:34 PM
 */

package mlnr.gui.dlg;

import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import mlnr.Measurement;

/**
 *
 * @author  Rob
 */
public class DialogSimpleDollieGenerator extends javax.swing.JDialog {

    ButtonGroup bgStep1 = new ButtonGroup();
    ButtonGroup bgStep2 = new ButtonGroup();
    ButtonGroup bgStep3 = new ButtonGroup();
    boolean bOk = false;
    /** Used for paths, use straight lines. */
    public static final int STRAIGHT = 1;
    /** Used for paths, use curved lines. */
    public static final int CURVED = 2;
    /** Used to determine what to generate, whole pie. */
    public static final int WHOLE_PIE = 1;
    /** Used to determine what to generate, slice. */
    public static final int SLICE = 2;
    /** Used to determine what to generate, both whole pie and slice. */
    public static final int BOTH = 3;
    /** Used to determine where to place the dollies at, current layer. */
    public static final int CURRENT_LAYER = 1;
    /** Used to determine where to place the dollies at, new layers. */
    public static final int NEW_LAYER = 2;
    /** Used to determine where to place the dollies at, new drawing. */
    public static final int NEW_DRAWING = 3;
    /** This is the number slices. */
    private int sliceCount = 0;
    /** This is the diameter in measurements. */
    private float diameter = 0.0f;

    /** Creates new form DialogDollie */
    public DialogSimpleDollieGenerator(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        bgStep1.add(jRadioButtonCurved);
        bgStep1.add(jRadioButtonStraight);

        bgStep2.add(jRadioButtonSlice);
        bgStep2.add(jRadioButtonBoth);
        bgStep2.add(jRadioButtonWholePie);

        bgStep3.add(jRadioButtonCurrentLayer);
        bgStep3.add(jRadioButtonNewDrawing);
        bgStep3.add(jRadioButtonNewLayer);

        jLabelMeasurement.setText(Measurement.getTextualName());
        jFormattedTextFieldDiameter.setValue(0.00);
        jFormattedTextFieldPiePieceCount.setValue(4);

        setLocation(DialogUtil.centerDialog(parent.getBounds(), getBounds()));        
    }

    /** Only the new drawing is selected.
     */
    public void enableNewDrawingOnly() {
        jRadioButtonCurrentLayer.setVisible(false);
        jRadioButtonNewLayer.setVisible(false);
        jRadioButtonNewDrawing.setSelected(true);
    }

    /** @return true if the user clicked on generate Dollie.
     */
    public boolean isOk() {
        return bOk;
    }

    /** This will determine where to place the dollies at.
     * @return CURRENT_LAYER, or NEW_LAYER, or NEW_DRAWING.
     */
    public int getPlacement() {
        if (jRadioButtonCurrentLayer.isSelected())
            return CURRENT_LAYER;
        if (jRadioButtonNewLayer.isSelected())
            return NEW_LAYER;
        if (jRadioButtonNewDrawing.isSelected())
            return NEW_DRAWING;

        throw new IllegalStateException("No radio button selected.");
    }

    /** This will get the users input for what the path should be.
     * @return CURVED or STRAIGHT.
     */
    public int getPath() {
        if (jRadioButtonCurved.isSelected())
            return CURVED;
        else
            return STRAIGHT;
    }

    /** This will return what needs to be generated.
     * @return WHOLE_PIE or SLICE or BOTH.
     */
    public int getGenerate() {

        if (jRadioButtonWholePie.isSelected())
            return WHOLE_PIE;
        if (jRadioButtonBoth.isSelected())
            return BOTH;
        if (jRadioButtonSlice.isSelected())
            return SLICE;

        throw new IllegalStateException("No radio button selected.");
    }

    /** @return the diameter of the dollie in measurements.
     */
    public float getDiameterMeasurement() {
        return diameter;
    }
    
    /** This will get the slice count.
     * @return the number of slices.
     */
    public int getSliceCount() {
        return sliceCount;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jRadioButtonStraight = new javax.swing.JRadioButton();
        jRadioButtonCurved = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jFormattedTextFieldPiePieceCount = new javax.swing.JFormattedTextField();
        jFormattedTextFieldDiameter = new javax.swing.JFormattedTextField();
        jLabelMeasurement = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jRadioButtonCurrentLayer = new javax.swing.JRadioButton();
        jRadioButtonNewLayer = new javax.swing.JRadioButton();
        jRadioButtonNewDrawing = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jRadioButtonBoth = new javax.swing.JRadioButton();
        jRadioButtonWholePie = new javax.swing.JRadioButton();
        jRadioButtonSlice = new javax.swing.JRadioButton();
        jButtonGenerateDollies = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Simple Doily Generator");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Step 1 - Simple Doily"));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mlnr/img/dlg/SimpleDollie.gif"))); // NOI18N

        jLabel2.setText("Outer Path:");

        jRadioButtonStraight.setText("Straight");
        jRadioButtonStraight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonStraightActionPerformed(evt);
            }
        });

        jRadioButtonCurved.setSelected(true);
        jRadioButtonCurved.setText("Curved");

        jLabel3.setText("Pie Piece Count:");

        jLabel4.setText("Diameter:");

        jFormattedTextFieldPiePieceCount.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jFormattedTextFieldPiePieceCount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldPiePieceCountActionPerformed(evt);
            }
        });

        jFormattedTextFieldDiameter.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));

        jLabelMeasurement.setText("jLabel5");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jRadioButtonStraight)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonCurved))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jFormattedTextFieldDiameter, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jFormattedTextFieldPiePieceCount, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelMeasurement, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jRadioButtonStraight)
                    .addComponent(jRadioButtonCurved))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jFormattedTextFieldPiePieceCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jFormattedTextFieldDiameter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelMeasurement))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Step 3 - Placement"));

        jRadioButtonCurrentLayer.setSelected(true);
        jRadioButtonCurrentLayer.setText("Current Layer");

        jRadioButtonNewLayer.setText("New Layer(s)");
        jRadioButtonNewLayer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonNewLayerActionPerformed(evt);
            }
        });

        jRadioButtonNewDrawing.setText("New Drawing(s)");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButtonCurrentLayer)
                    .addComponent(jRadioButtonNewLayer)
                    .addComponent(jRadioButtonNewDrawing))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jRadioButtonCurrentLayer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonNewLayer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonNewDrawing)
                .addContainerGap(138, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Step 2 - Generate"));

        jRadioButtonBoth.setSelected(true);
        jRadioButtonBoth.setText("Both - Whole + Pie Piece");

        jRadioButtonWholePie.setText("Whole Pie Only");
        jRadioButtonWholePie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonWholePieActionPerformed(evt);
            }
        });

        jRadioButtonSlice.setText("Pie Piece Only");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jRadioButtonBoth)
            .addComponent(jRadioButtonWholePie)
            .addComponent(jRadioButtonSlice)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jRadioButtonBoth)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonWholePie)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonSlice)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jButtonGenerateDollies.setText("Generate Doily");
        jButtonGenerateDollies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGenerateDolliesActionPerformed(evt);
            }
        });

        jButtonCancel.setText("Cancel");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(265, Short.MAX_VALUE)
                .addComponent(jButtonCancel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonGenerateDollies)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonGenerateDollies)
                    .addComponent(jButtonCancel))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jRadioButtonStraightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonStraightActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_jRadioButtonStraightActionPerformed

private void jRadioButtonNewLayerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonNewLayerActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_jRadioButtonNewLayerActionPerformed

private void jRadioButtonWholePieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonWholePieActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_jRadioButtonWholePieActionPerformed

private void jButtonGenerateDolliesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGenerateDolliesActionPerformed
// TODO add your handling code here:    
    sliceCount = Integer.parseInt(jFormattedTextFieldPiePieceCount.getValue().toString());
    diameter = Measurement.convReal(Float.parseFloat(jFormattedTextFieldDiameter.getValue().toString()));

    // Validate the number of slices.
    if (sliceCount < 4) {
        JOptionPane.showMessageDialog(this, "Please choose a value greater than equal to 4 for pie piece count.");
        return;
    }
    
    // Validate the size of the diameter.
    if (diameter <= 0) {
        JOptionPane.showMessageDialog(this, "Please choose a value greater than 0 for the diameter.");
        return;
    }

    bOk = true;
    setVisible(false);
}//GEN-LAST:event_jButtonGenerateDolliesActionPerformed

private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
// TODO add your handling code here:
    setVisible(false);
}//GEN-LAST:event_jButtonCancelActionPerformed

private void jFormattedTextFieldPiePieceCountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldPiePieceCountActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_jFormattedTextFieldPiePieceCountActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                DialogSimpleDollieGenerator dialog = new DialogSimpleDollieGenerator(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }

                });
                dialog.setVisible(true);
            }

        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonGenerateDollies;
    private javax.swing.JFormattedTextField jFormattedTextFieldDiameter;
    private javax.swing.JFormattedTextField jFormattedTextFieldPiePieceCount;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelMeasurement;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButtonBoth;
    private javax.swing.JRadioButton jRadioButtonCurrentLayer;
    private javax.swing.JRadioButton jRadioButtonCurved;
    private javax.swing.JRadioButton jRadioButtonNewDrawing;
    private javax.swing.JRadioButton jRadioButtonNewLayer;
    private javax.swing.JRadioButton jRadioButtonSlice;
    private javax.swing.JRadioButton jRadioButtonStraight;
    private javax.swing.JRadioButton jRadioButtonWholePie;
    // End of variables declaration//GEN-END:variables
}
