/*
 * DialogResizeSelection.java
 *
 * Created on February 20, 2006, 3:50 PM
 */

package mlnr.gui.tool.dlg;

import java.text.DecimalFormat;
import javax.swing.*;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.NumberFormatter;

import mlnr.Measurement;
import mlnr.util.DefaultExceptionHandler;

/**
 *
 * @author  Robert Molnar
 */
public class DialogResizeSelection extends javax.swing.JDialog {
    /** true: measurement being used, false: percentage is being used. */
    boolean measurementOrPercentage = true;
    boolean isResize = false;
    ButtonGroup bg = new ButtonGroup();
    /** This is x / y ratio. */
    float ratio_x_to_y;
    /** This is y / x ratio. */
    float ratio_y_to_x;
    /** This is the current size of the selection. */
    float currWidth;
    float currHeight;
    
    /** Creates new form DialogResizeSelection */
    public DialogResizeSelection(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        getRootPane().setDefaultButton(jButtonResize);
        
        jLabelTextWdith.setText(Measurement.getTextualLongName());
        jLabelTextHeight.setText(Measurement.getTextualLongName());
        jRadioButtonMeasurement.setText(Measurement.getTextualLongName());
        
        bg.add(jRadioButtonMeasurement);
        bg.add(jRadioButtonDegree);
        jRadioButtonMeasurement.setSelected(true);
        jCheckBoxUniform.setSelected(true);
        
        jFormattedTextFieldWidth.setFormatterFactory(new DefaultFormatterFactory(new NumberFormatter(new DecimalFormat("#.##"))));
        jFormattedTextFieldHeight.setFormatterFactory(new DefaultFormatterFactory(new NumberFormatter(new DecimalFormat("#.##"))));
        
        setLocationRelativeTo(null); // center dialog.
    }
    
    /** @return true if the user clicked on resize, thus true if to resize the selected vertices, else false.
     */
    public boolean isResize() {
        return isResize;
    }
    
    /** This will set the current size label.
     * @param width is the current size of the selected items in measurement.
     * @param height is the current size of the sekected items in measurement.
     */
    public void setCurrentSize(float width, float height) {
        currWidth = width;
        currHeight = height;
        
        float dx = currWidth;
        float dy = currHeight;
        if (dx < 0.000001f)
            dx = 0.000001f;
        if (dy < 0.000001f)
            dy = 0.000001f;
        
        ratio_x_to_y = dx / dy;
        ratio_y_to_x = dy / dx;
        
        // Set the current size of the selected vertices.
        jLabelWidth.setText("" + Measurement.convertMeasurement(currWidth, 2));
        jLabelHeight.setText("" + Measurement.convertMeasurement(currHeight, 2));
        
        // Set the resize to the current size.
        jFormattedTextFieldWidth.setValue(Measurement.convertMeasurement(currWidth, 2));
        jFormattedTextFieldHeight.setValue(Measurement.convertMeasurement(currHeight, 2));
    }
    
    /** @return The width of the new resize in measurements.
     */
    public float getWidthInMeasurements() {
        if (measurementOrPercentage)
            return Measurement.convReal(Float.parseFloat(jFormattedTextFieldWidth.getValue().toString()));
        else {
            float percentWidth = Float.parseFloat(jFormattedTextFieldWidth.getValue().toString()) / 100;
            return currWidth * percentWidth;
        }
    }
    
    /** @return The height of the new resize in measurements.
     */
    public float getHeightInMeasurements() {
        if (measurementOrPercentage)
            return Measurement.convReal(Float.parseFloat(jFormattedTextFieldHeight.getValue().toString()));
        else {
            float percentHeight = Float.parseFloat(jFormattedTextFieldHeight.getValue().toString()) / 100;
            return currHeight * percentHeight;
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelWidth = new javax.swing.JLabel();
        jLabelHeight = new javax.swing.JLabel();
        jLabelTextWdith = new javax.swing.JLabel();
        jLabelTextHeight = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jCheckBoxUniform = new javax.swing.JCheckBox();
        jRadioButtonMeasurement = new javax.swing.JRadioButton();
        jRadioButtonDegree = new javax.swing.JRadioButton();
        jFormattedTextFieldWidth = new javax.swing.JFormattedTextField();
        jFormattedTextFieldHeight = new javax.swing.JFormattedTextField();
        jButtonCancel = new javax.swing.JButton();
        jButtonResize = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Resize Operation");
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Current Dimensions"));
        jLabel1.setText("Width:");

        jLabel2.setText("Height:");

        jLabelWidth.setText("jLabel3");

        jLabelHeight.setText("jLabel3");

        jLabelTextWdith.setText("jLabel3");

        jLabelTextHeight.setText("jLabel4");

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel1)
                    .add(jLabel2))
                .add(49, 49, 49)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jLabelWidth, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 90, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabelTextWdith, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 80, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jLabelHeight, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 90, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabelTextHeight, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 80, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .add(76, 76, 76))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(jLabelWidth, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(jLabelTextWdith, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabelHeight, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabelTextHeight, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Resize Dimensions"));
        jLabel3.setText("Width:");

        jLabel4.setText("Height:");

        jCheckBoxUniform.setText("Uniform Resize");

        jRadioButtonMeasurement.setText("Millimeters");
        jRadioButtonMeasurement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMeasurementActionPerformed(evt);
            }
        });

        jRadioButtonDegree.setText("Percentage");
        jRadioButtonDegree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonDegreeActionPerformed(evt);
            }
        });

        jFormattedTextFieldWidth.setText("jFormattedTextField1");
        jFormattedTextFieldWidth.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jFormattedTextFieldWidthKeyReleased(evt);
            }
        });

        jFormattedTextFieldHeight.setText("jFormattedTextField2");
        jFormattedTextFieldHeight.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jFormattedTextFieldHeightKeyReleased(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jCheckBoxUniform, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 160, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                        .add(jPanel2Layout.createSequentialGroup()
                            .add(jLabel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 70, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                            .add(jFormattedTextFieldHeight, 0, 0, Short.MAX_VALUE))
                        .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel2Layout.createSequentialGroup()
                            .add(jLabel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 70, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                            .add(jFormattedTextFieldWidth, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 85, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                .add(76, 76, 76)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jRadioButtonMeasurement, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jRadioButtonDegree)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jRadioButtonMeasurement)
                    .add(jFormattedTextFieldWidth, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jRadioButtonDegree)
                    .add(jFormattedTextFieldHeight, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jCheckBoxUniform)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButtonCancel.setText("Cancel");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        jButtonResize.setText("Resize");
        jButtonResize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResizeActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .addContainerGap()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .add(jButtonCancel)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jButtonResize)))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jButtonResize)
                    .add(jButtonCancel))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-380)/2, (screenSize.height-288)/2, 380, 288);
    }// </editor-fold>//GEN-END:initComponents
    
    private void jFormattedTextFieldHeightKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFormattedTextFieldHeightKeyReleased
// TODO add your handling code here:
        try {
            jFormattedTextFieldHeight.commitEdit();
        } catch (Exception e) {
            // What to do?
        }
        
        if (jCheckBoxUniform.isSelected()) {
            if (jRadioButtonMeasurement.isSelected()) {
                try {
                    float fHeight = Float.parseFloat(jFormattedTextFieldHeight.getValue().toString());
                    fHeight = fHeight * ratio_x_to_y;
                    jFormattedTextFieldWidth.setValue(fHeight);
                } catch (Exception e) {
                    // What to do?
                }
            } else
                jFormattedTextFieldWidth.setValue(Float.parseFloat(jFormattedTextFieldHeight.getValue().toString()));
        }
        
    }//GEN-LAST:event_jFormattedTextFieldHeightKeyReleased
    
    private void jFormattedTextFieldWidthKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFormattedTextFieldWidthKeyReleased
// TODO add your handling code here:
        try {
            jFormattedTextFieldWidth.commitEdit();
        } catch (Exception e) {
            System.err.println("Exception: " + e);
        }
        
        if (jCheckBoxUniform.isSelected()) {
            if (jRadioButtonMeasurement.isSelected()) {
                try {
                    float fWidth = Float.parseFloat(jFormattedTextFieldWidth.getValue().toString());
                    fWidth = fWidth * ratio_y_to_x;
                    jFormattedTextFieldHeight.setValue(fWidth);
                } catch (Exception e) {
                    System.err.println(e);
                }
            } else
                jFormattedTextFieldHeight.setValue(Float.parseFloat(jFormattedTextFieldWidth.getValue().toString()));
        }
        
    }//GEN-LAST:event_jFormattedTextFieldWidthKeyReleased
    
    private void jRadioButtonDegreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonDegreeActionPerformed
        // Convert measurement to percentage.
        if (measurementOrPercentage) {
            float fWidth = Measurement.convReal(Float.parseFloat(jFormattedTextFieldWidth.getValue().toString()));
            float fHeight = Measurement.convReal(Float.parseFloat(jFormattedTextFieldHeight.getValue().toString()));
            
            // Get a percentage.
            float percentWidth = (fWidth / currWidth) * 100.0f;
            float percentHeight = (fHeight / currHeight) * 100.0f;
            
            // Now update the fields to percentages.
            jFormattedTextFieldWidth.setValue(percentWidth);
            jFormattedTextFieldHeight.setValue(percentHeight);
        }
        measurementOrPercentage = false;
        
    }//GEN-LAST:event_jRadioButtonDegreeActionPerformed
    
    private void jRadioButtonMeasurementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMeasurementActionPerformed
        // Convert percentage to measurement.
        if (measurementOrPercentage == false) {
            float percentWidth = Float.parseFloat(jFormattedTextFieldWidth.getValue().toString()) / 100.0f;
            float percentHeight = Float.parseFloat(jFormattedTextFieldHeight.getValue().toString()) / 100.0f;
            
            float newWidth = currWidth * percentWidth;
            float newHeight = currHeight * percentHeight;
            
            // Now update the fields to measurements.
            jFormattedTextFieldWidth.setValue(newWidth);
            jFormattedTextFieldHeight.setValue(newHeight);
        }
        measurementOrPercentage = true;
    }//GEN-LAST:event_jRadioButtonMeasurementActionPerformed
    
    private void doubleTextFieldHeightKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_doubleTextFieldHeightKeyReleased
// TODO add your handling code here:
        
    }//GEN-LAST:event_doubleTextFieldHeightKeyReleased
    
    private void doubleTextFieldWidthKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_doubleTextFieldWidthKeyReleased
// TODO add your handling code here:
        
    }//GEN-LAST:event_doubleTextFieldWidthKeyReleased
    
    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        setVisible(false);
    }//GEN-LAST:event_jButtonCancelActionPerformed
    
    private void jButtonResizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResizeActionPerformed
        isResize = true;
        setVisible(false);
    }//GEN-LAST:event_jButtonResizeActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DialogResizeSelection(new javax.swing.JFrame(), true).setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonResize;
    private javax.swing.JCheckBox jCheckBoxUniform;
    private javax.swing.JFormattedTextField jFormattedTextFieldHeight;
    private javax.swing.JFormattedTextField jFormattedTextFieldWidth;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelHeight;
    private javax.swing.JLabel jLabelTextHeight;
    private javax.swing.JLabel jLabelTextWdith;
    private javax.swing.JLabel jLabelWidth;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButtonDegree;
    private javax.swing.JRadioButton jRadioButtonMeasurement;
    // End of variables declaration//GEN-END:variables
    
}
