/*
 * DialogGetRotate.java
 *
 * Created on August 24, 2005, 5:37 PM
 */

package mlnr.gui.tool.dlg;

import java.text.DecimalFormat;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.NumberFormatter;
import mlnr.gui.dlg.DialogUtil;

/**
 *
 * @author  Robert Molnar II
 */
public class DialogGetRotate extends javax.swing.JDialog {
    boolean ok = false;
    
    
    /**
     * Creates new form DialogGetRotate
     */
    public DialogGetRotate(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        jFormattedTextFieldDegree.setFormatterFactory(new DefaultFormatterFactory(new NumberFormatter(new DecimalFormat("#.##"))));
        setRadian(0.0f);
                
        getRootPane().setDefaultButton(jButtonRotateTo);
        setLocation(DialogUtil.centerDialog(parent.getBounds(), getBounds()));
    }
    
    /** Set the radian for this dialog box.
     * @param rad is the radian for this dialog box.
     */
    public void setRadian(float rad) {
        // Set the field the degree.
        float degree = (float)Math.toDegrees(rad);
//        if (rad != 0.0f)
//            degree = 360 - degree;        
        jFormattedTextFieldDegree.setValue(Float.parseFloat(String.format("%.2f", degree)));
    }
    
    /** @return true if the user wanted to rotate.
     */
    public boolean isOk() {
        return ok;
    }
    
    /** This will get the radians to rotate the object to.
     * @return the radian to rotate object to.
     */
    public float getRadian() {
        String str = jFormattedTextFieldDegree.getText();
        if (str == null || str.equals(""))
            return 0.0f;
        
        float degree = Float.parseFloat(str);
        return (float)Math.toRadians(360.0f - degree);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jLabel1 = new javax.swing.JLabel();
        jFormattedTextFieldDegree = new javax.swing.JFormattedTextField();
        jButtonCancel = new javax.swing.JButton();
        jButtonRotateTo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Enter Degrees");
        jLabel1.setText("Please Enter Degrees To Rotate To:");

        jFormattedTextFieldDegree.setText("jFormattedTextField1");

        jButtonCancel.setText("Cancel");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        jButtonRotateTo.setText("Rotate To");
        jButtonRotateTo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRotateToActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(167, 167, 167)
                        .add(jButtonCancel)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jButtonRotateTo))
                    .add(layout.createSequentialGroup()
                        .add(jLabel1)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jFormattedTextFieldDegree, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(jFormattedTextFieldDegree, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jButtonRotateTo)
                    .add(jButtonCancel))
                .addContainerGap())
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void integerTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_integerTextField1ActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_integerTextField1ActionPerformed
    
    private void jButtonRotateToActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRotateToActionPerformed
// TODO add your handling code here:
        ok = true;
        setVisible(false);
    }//GEN-LAST:event_jButtonRotateToActionPerformed
    
    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
// TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButtonCancelActionPerformed
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DialogGetRotate(new javax.swing.JFrame(), true).setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonRotateTo;
    private javax.swing.JFormattedTextField jFormattedTextFieldDegree;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
    
}
