/*
 * AddPointPanel.java
 *
 * Created on August 17, 2005, 9:43 PM
 */

package mlnr.gui.tool.opt;

import javax.swing.*;

/**
 *
 * @author  Robert Molnar II
 */
public class AddPointPanel extends javax.swing.JPanel {
    ButtonGroup buttonGroup = new ButtonGroup();
    
    /** Creates new form AddPointPanel */
    public AddPointPanel() {
        initComponents();
        
        buttonGroup.add(jRadioButtonCurrentLayer);
        buttonGroup.add(jRadioButtonAllVisibleLayers);
        jRadioButtonCurrentLayer.setSelected(true);
    }
    
    /** @return true if the current layer is selected.
     */
    public boolean isCurrentLayer() {
        return jRadioButtonCurrentLayer.isSelected();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jRadioButtonCurrentLayer = new javax.swing.JRadioButton();
        jRadioButtonAllVisibleLayers = new javax.swing.JRadioButton();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.BorderLayout(10, 10));

        jPanel1.setBorder(new javax.swing.border.TitledBorder("Add Point Options"));
        jPanel2.setLayout(new java.awt.GridLayout(2, 1));

        jPanel2.setBorder(new javax.swing.border.TitledBorder("Add Point to Which Layers"));
        jRadioButtonCurrentLayer.setText("Current Layer");
        jPanel2.add(jRadioButtonCurrentLayer);

        jRadioButtonAllVisibleLayers.setText("All Visible Layers");
        jPanel2.add(jRadioButtonAllVisibleLayers);

        jPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);

        add(jPanel1, java.awt.BorderLayout.CENTER);

    }
    // </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButtonAllVisibleLayers;
    private javax.swing.JRadioButton jRadioButtonCurrentLayer;
    // End of variables declaration//GEN-END:variables
    
}
