/*
 * DeletePanel.java
 *
 * Created on August 16, 2005, 10:31 PM
 */

package mlnr.gui.tool.opt;

import javax.swing.ButtonGroup;

/**
 *
 * @author  Robert Molnar II
 */
public class DeletePanel extends javax.swing.JPanel {
    private ButtonGroup radioSelect = new ButtonGroup();
    private ButtonGroup radioLayer = new ButtonGroup();
    
    /** Creates new form DeletePanel */
    public DeletePanel() {
        initComponents();
        
        radioSelect.add(jRadioButtonEverything);
        radioSelect.add(jRadioButtonLinesCurves);
        radioSelect.add(jRadioButtonControlPoints);
        jRadioButtonControlPoints.setSelected(true);
        
        
        radioLayer.add(jRadioButtonCurrentLayer);
        radioLayer.add(jRadioButtonAllVisibleLayers);
        jRadioButtonCurrentLayer.setSelected(true);
    }
    
    public boolean isSelectObject() {
        return jRadioButtonEverything.isSelected();
    }
    
    public boolean isSelectLine() {
        return jRadioButtonLinesCurves.isSelected();
    }
    
    public boolean isSelectVertex() {
        return jRadioButtonControlPoints.isSelected();
    }
    
    public boolean isCurrentLayer() {
        return jRadioButtonCurrentLayer.isSelected();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jRadioButtonEverything = new javax.swing.JRadioButton();
        jRadioButtonLinesCurves = new javax.swing.JRadioButton();
        jRadioButtonControlPoints = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jRadioButtonCurrentLayer = new javax.swing.JRadioButton();
        jRadioButtonAllVisibleLayers = new javax.swing.JRadioButton();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel1.setBorder(new javax.swing.border.TitledBorder("Delete Options"));
        jPanel2.setLayout(new java.awt.GridLayout(3, 1));

        jPanel2.setBorder(new javax.swing.border.TitledBorder("Selection Method"));
        jRadioButtonEverything.setText("Object");
        jPanel2.add(jRadioButtonEverything);

        jRadioButtonLinesCurves.setText("Line & Curve");
        jPanel2.add(jRadioButtonLinesCurves);

        jRadioButtonControlPoints.setText("Point");
        jPanel2.add(jRadioButtonControlPoints);

        jPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel3.setLayout(new java.awt.GridLayout(2, 1));

        jPanel3.setBorder(new javax.swing.border.TitledBorder("Layer Selection"));
        jRadioButtonCurrentLayer.setText("Current Layer");
        jPanel3.add(jRadioButtonCurrentLayer);

        jRadioButtonAllVisibleLayers.setText("All Visible Layers");
        jPanel3.add(jRadioButtonAllVisibleLayers);

        jPanel1.add(jPanel3, java.awt.BorderLayout.SOUTH);

        add(jPanel1, java.awt.BorderLayout.CENTER);

    }
    // </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButtonAllVisibleLayers;
    private javax.swing.JRadioButton jRadioButtonControlPoints;
    private javax.swing.JRadioButton jRadioButtonCurrentLayer;
    private javax.swing.JRadioButton jRadioButtonEverything;
    private javax.swing.JRadioButton jRadioButtonLinesCurves;
    // End of variables declaration//GEN-END:variables
    
}
