/*
 * MirrorPanel.java
 *
 * Created on January 12, 2006, 2:43 PM
 */

package mlnr.gui.tool.opt;

import javax.swing.*;
import mlnr.gui.tool.ToolMirror;

/**
 *
 * @author  Robert Molnar
 */
public class MirrorPanel extends javax.swing.JPanel {
    ButtonGroup buttonGroup = new ButtonGroup();
    ToolMirror tMirror;
        
    /** Creates new form MirrorPanel */
    public MirrorPanel() {
        initComponents();
        
        buttonGroup.add(jRadioButtonDegree);
        buttonGroup.add(jRadioButtonHorizontal);
        buttonGroup.add(jRadioButtonVertical);
        jRadioButtonVertical.setSelected(true);
        jFormattedTextField1.setValue(0.00f);
    }
    
    public void setMirrorTool(ToolMirror tMirror) {
        this.tMirror = tMirror;
    }
    
    public boolean isDirectionDegree() {
        return jRadioButtonDegree.isSelected();
    }
    
    public boolean isDirectionHorizontal() {
        return jRadioButtonHorizontal.isSelected();
    }
    
    public boolean isDirectionVertical() {
        return jRadioButtonVertical.isSelected();
    }
    
    public float getRadian() {
        if (jRadioButtonHorizontal.isSelected())
            return 0.0f;
        else if (jRadioButtonVertical.isSelected())
            return (float)Math.PI / 2;
        else if (jRadioButtonDegree.isSelected())
            return (float)Math.toRadians(360.0f - Float.parseFloat(jFormattedTextField1.getValue().toString()));
        else
            throw new IllegalStateException("MirrorPanel::getRadian() unknown mirror method.");
    }
    
    public boolean isDegree() {
        return jRadioButtonDegree.isSelected();
        
    }   
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanelMirrorMethod = new javax.swing.JPanel();
        jRadioButtonVertical = new javax.swing.JRadioButton();
        jRadioButtonHorizontal = new javax.swing.JRadioButton();
        jRadioButtonDegree = new javax.swing.JRadioButton();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jButtonResetPointToCenter = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });
        addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                formComponentAdded(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Mirror Options"));

        jPanelMirrorMethod.setBorder(javax.swing.BorderFactory.createTitledBorder("Mirror Methods"));

        jRadioButtonVertical.setText("Vertical");
        jRadioButtonVertical.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonVerticalActionPerformed(evt);
            }
        });

        jRadioButtonHorizontal.setText("Horizontal");
        jRadioButtonHorizontal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonHorizontalActionPerformed(evt);
            }
        });

        jRadioButtonDegree.setText("Degree");
        jRadioButtonDegree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonDegreeActionPerformed(evt);
            }
        });

        jFormattedTextField1.setText("jFormattedTextField1");
        jFormattedTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jFormattedTextField1KeyReleased(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanelMirrorMethodLayout = new org.jdesktop.layout.GroupLayout(jPanelMirrorMethod);
        jPanelMirrorMethod.setLayout(jPanelMirrorMethodLayout);
        jPanelMirrorMethodLayout.setHorizontalGroup(
            jPanelMirrorMethodLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelMirrorMethodLayout.createSequentialGroup()
                .add(jPanelMirrorMethodLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jRadioButtonVertical)
                    .add(jRadioButtonHorizontal)
                    .add(jPanelMirrorMethodLayout.createSequentialGroup()
                        .add(jRadioButtonDegree)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jFormattedTextField1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 69, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanelMirrorMethodLayout.setVerticalGroup(
            jPanelMirrorMethodLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelMirrorMethodLayout.createSequentialGroup()
                .add(jRadioButtonVertical)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jRadioButtonHorizontal)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanelMirrorMethodLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jRadioButtonDegree)
                    .add(jFormattedTextField1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Method Options"));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jButtonResetPointToCenter.setText("Reset Point To Center");
        jButtonResetPointToCenter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResetPointToCenterActionPerformed(evt);
            }
        });
        jPanel4.add(jButtonResetPointToCenter);

        jPanel3.add(jPanel4, java.awt.BorderLayout.SOUTH);

        jLabel1.setText("Use Right Click To Set Mirror Point");
        jPanel3.add(jLabel1, java.awt.BorderLayout.NORTH);

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelMirrorMethod, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(jPanel3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jPanelMirrorMethod, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jFormattedTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFormattedTextField1KeyReleased
// TODO add your handling code here:
        try {
            jFormattedTextField1.commitEdit();
        } catch (Exception e) {
            tMirror.setRadian(0.00f);
            return;
        }
        
        tMirror.setRadian(getRadian());
        
    }//GEN-LAST:event_jFormattedTextField1KeyReleased
    
    private void formComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_formComponentAdded
        
    }//GEN-LAST:event_formComponentAdded
    
    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained

    }//GEN-LAST:event_formFocusGained
    
    private void integerTextFieldDegreeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_integerTextFieldDegreeKeyReleased
        tMirror.setRadian(getRadian());
        
    }//GEN-LAST:event_integerTextFieldDegreeKeyReleased
    
    private void integerTextFieldDegreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_integerTextFieldDegreeActionPerformed
        if (jRadioButtonDegree.isSelected() == false)
            jRadioButtonDegree.setSelected(true);
        tMirror.setRadian(getRadian());
        
    }//GEN-LAST:event_integerTextFieldDegreeActionPerformed
    
    private void jRadioButtonDegreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonDegreeActionPerformed
        tMirror.setRadian(getRadian());
        
    }//GEN-LAST:event_jRadioButtonDegreeActionPerformed
    
    private void jRadioButtonHorizontalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonHorizontalActionPerformed
        tMirror.setRadian(0.00f);
        
    }//GEN-LAST:event_jRadioButtonHorizontalActionPerformed
    
    private void jRadioButtonVerticalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonVerticalActionPerformed
        tMirror.setRadian((float)Math.PI / 2);
        
    }//GEN-LAST:event_jRadioButtonVerticalActionPerformed
    
    private void jButtonResetPointToCenterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetPointToCenterActionPerformed
        tMirror.resetPointToCenter();
        
    }//GEN-LAST:event_jButtonResetPointToCenterActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonResetPointToCenter;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanelMirrorMethod;
    private javax.swing.JRadioButton jRadioButtonDegree;
    private javax.swing.JRadioButton jRadioButtonHorizontal;
    private javax.swing.JRadioButton jRadioButtonVertical;
    // End of variables declaration//GEN-END:variables
    
}
