/*
 * PullLineApartPanel.java
 *
 * Created on September 11, 2006, 3:11 PM
 */

package mlnr.gui.tool.opt;

import javax.swing.ButtonGroup;

/**
 *
 * @author  Robert Molnar II
 */
public class PullLineApartPanel extends javax.swing.JPanel {
    ButtonGroup buttonSelection = new ButtonGroup();
    
    
    /** Creates new form PullLineApartPanel */
    public PullLineApartPanel() {
        initComponents();
        
        buttonSelection.add(jRadioButtonAllVisibleLayers);
        buttonSelection.add(jRadioButtonCurrentLayer);
        jRadioButtonCurrentLayer.setSelected(true);
        
    }
    
    public boolean isCurrentLayer() {
        return jRadioButtonCurrentLayer.isSelected();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel4 = new javax.swing.JPanel();
        jRadioButtonCurrentLayer = new javax.swing.JRadioButton();
        jRadioButtonAllVisibleLayers = new javax.swing.JRadioButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Pull Line Apart Options"));
        jPanel4.setLayout(new java.awt.BorderLayout());

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Layer Selection"));
        jRadioButtonCurrentLayer.setText("Current Layer");
        jPanel4.add(jRadioButtonCurrentLayer, java.awt.BorderLayout.SOUTH);

        jRadioButtonAllVisibleLayers.setText("All Visible Layers");
        jPanel4.add(jRadioButtonAllVisibleLayers, java.awt.BorderLayout.NORTH);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRadioButtonAllVisibleLayers;
    private javax.swing.JRadioButton jRadioButtonCurrentLayer;
    // End of variables declaration//GEN-END:variables
    
}
