/*
 * SelectPanel.java
 *
 * Created on August 18, 2005, 6:40 PM
 */

package mlnr.gui.tool.opt;

import javax.swing.*;

/**
 *
 * @author  Robert Molnar II
 */
public class SelectPanel extends javax.swing.JPanel {
    ButtonGroup buttonSelection = new ButtonGroup();
    ButtonGroup buttonLayer = new ButtonGroup();
    
    /** Creates new form SelectPanel */
    public SelectPanel() {
        initComponents();
        
        buttonSelection.add(jRadioButtonEverything);
        buttonSelection.add(jRadioButtonLinesCurves);
        buttonSelection.add(jRadioButtonControlPoints);
        buttonSelection.add(jRadioButtonAllItem);
        jRadioButtonControlPoints.setSelected(true);
        
        buttonLayer.add(jRadioButtonCurrentLayer);
        buttonLayer.add(jRadioButtonAllVisibleLayers);
        jRadioButtonCurrentLayer.setSelected(true);
    }
    
    public boolean isSelectAllItems() {
        return jRadioButtonAllItem.isSelected();
    }
    
    public boolean isSelectGraph() {
        return jRadioButtonEverything.isSelected();
    }
    
    public boolean isSelectLine() {
        return jRadioButtonLinesCurves.isSelected();
    }
    
    public boolean isSelectPoint() {
        return jRadioButtonControlPoints.isSelected();
    }
    
    public boolean isCurrentLayer() {
        return jRadioButtonCurrentLayer.isSelected();
    }    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jRadioButtonAllItem = new javax.swing.JRadioButton();
        jRadioButtonEverything = new javax.swing.JRadioButton();
        jRadioButtonLinesCurves = new javax.swing.JRadioButton();
        jRadioButtonControlPoints = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        jRadioButtonCurrentLayer = new javax.swing.JRadioButton();
        jRadioButtonAllVisibleLayers = new javax.swing.JRadioButton();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Selection Options"));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Selection Method"));
        jPanel3.setLayout(new java.awt.GridLayout(4, 1));

        jRadioButtonAllItem.setText("All Items");
        jPanel3.add(jRadioButtonAllItem);

        jRadioButtonEverything.setText("Object");
        jPanel3.add(jRadioButtonEverything);

        jRadioButtonLinesCurves.setText("Line & Curve");
        jPanel3.add(jRadioButtonLinesCurves);

        jRadioButtonControlPoints.setText("Point");
        jPanel3.add(jRadioButtonControlPoints);

        jPanel2.add(jPanel3, java.awt.BorderLayout.CENTER);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Layer Selection"));
        jPanel4.setLayout(new java.awt.BorderLayout());

        jRadioButtonCurrentLayer.setText("Current Layer");
        jPanel4.add(jRadioButtonCurrentLayer, java.awt.BorderLayout.SOUTH);

        jRadioButtonAllVisibleLayers.setText("All Visible Layers");
        jPanel4.add(jRadioButtonAllVisibleLayers, java.awt.BorderLayout.NORTH);

        jPanel2.add(jPanel4, java.awt.BorderLayout.SOUTH);

        jPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRadioButtonAllItem;
    private javax.swing.JRadioButton jRadioButtonAllVisibleLayers;
    private javax.swing.JRadioButton jRadioButtonControlPoints;
    private javax.swing.JRadioButton jRadioButtonCurrentLayer;
    private javax.swing.JRadioButton jRadioButtonEverything;
    private javax.swing.JRadioButton jRadioButtonLinesCurves;
    // End of variables declaration//GEN-END:variables
    
}
